//debug with ai
const studentData = [
    {
        id: 1,
        name: "Student1",
        year: 2020,
        department: "CSE",
        course: "B.Tech",
        specialization: "AI",
        cgpa: 8.7,
        company: "Google",
        ctc: 12,
        jobRole: "Software Engineer",
        jobLocation: "Bangalore",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 2,
        name: "Student2",
        year: 2020,
        department: "CSE",
        course: "M.Tech",
        specialization: "Cloud Computing",
        cgpa: 9.2,
        company: "Amazon",
        ctc: 15,
        jobRole: "Cloud Engineer",
        jobLocation: "Hyderabad",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 3,
        name: "Student3",
        year: 2020,
        department: "ECE",
        course: "B.Tech",
        specialization: "VLSI Design",
        cgpa: 7.8,
        company: "Intel",
        ctc: 8,
        jobRole: "Hardware Engineer",
        jobLocation: "Bangalore",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 4,
        name: "Student4",
        year: 2021,
        department: "ECE",
        course: "M.Tech",
        specialization: "Communication Systems",
        cgpa: 8.1,
        company: "Qualcomm",
        ctc: 10,
        jobRole: "Communication Engineer",
        jobLocation: "Hyderabad",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 5,
        name: "Student5",
        year: 2021,
        department: "ME",
        course: "B.Tech",
        specialization: "Thermal Engineering",
        cgpa: 7.5,
        company: "Tata Motors",
        ctc: 6,
        jobRole: "Mechanical Engineer",
        jobLocation: "Mumbai",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 6,
        name: "Student6",
        year: 2020,
        department: "ECE",
        course: "B.Tech",
        specialization: "Communication Systems",
        cgpa: 7.49,
        company: "Qualcomm",
        ctc: 13,
        jobRole: "Data Scientist",
        jobLocation: "Mumbai",
        placementType: "Off-Campus",
        college: "ABC University"
    },
    {
        id: 7,
        name: "Student7",
        year: 2022,
        department: "ME",
        course: "B.Tech",
        specialization: "Thermal Engineering",
        cgpa: 8.12,
        company: "Facebook",
        ctc: 20,
        jobRole: "Network Engineer",
        jobLocation: "Chennai",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 8,
        name: "Student8",
        year: 2022,
        department: "CSE",
        course: "B.Tech",
        specialization: "ML",
        cgpa: 8.72,
        company: "Cisco",
        ctc: 14,
        jobRole: "Communication Engineer",
        jobLocation: "Hyderabad",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 9,
        name: "Student9",
        year: 2022,
        department: "ECE",
        course: "M.Tech",
        specialization: "Embedded Systems",
        cgpa: 8.07,
        company: "Qualcomm",
        ctc: 6,
        jobRole: "Software Engineer",
        jobLocation: "Bangalore",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 10,
        name: "Student10",
        year: 2020,
        department: "ME",
        course: "B.Tech",
        specialization: "Thermal Engineering",
        cgpa: 9.02,
        company: "Amazon",
        ctc: 16,
        jobRole: "Software Engineer",
        jobLocation: "Hyderabad",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 11,
        name: "Student11",
        year: 2021,
        department: "ME",
        course: "B.Tech",
        specialization: "Manufacturing",
        cgpa: 8.46,
        company: "Amazon",
        ctc: 15,
        jobRole: "Network Engineer",
        jobLocation: "Pune",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 12,
        name: "Student12",
        year: 2020,
        department: "ECE",
        course: "B.Tech",
        specialization: "Embedded Systems",
        cgpa: 6.17,
        company: "Microsoft",
        ctc: 7,
        jobRole: "Communication Engineer",
        jobLocation: "Delhi",
        placementType: "Off-Campus",
        college: "ABC University"
    },
    {
        id: 13,
        name: "Student13",
        year: 2020,
        department: "CSE",
        course: "M.Tech",
        specialization: "Cybersecurity",
        cgpa: 9.49,
        company: "Qualcomm",
        ctc: 11,
        jobRole: "Network Engineer",
        jobLocation: "Pune",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 14,
        name: "Student14",
        year: 2021,
        department: "ME",
        course: "M.Tech",
        specialization: "Design Engineering",
        cgpa: 6.19,
        company: "Microsoft",
        ctc: 8,
        jobRole: "Data Scientist",
        jobLocation: "Bangalore",
        placementType: "Off-Campus",
        college: "ABC University"
    },
    {
        id: 15,
        name: "Student15",
        year: 2022,
        department: "CSE",
        course: "B.Tech",
        specialization: "Cloud Computing",
        cgpa: 7.93,
        company: "Oracle",
        ctc: 13,
        jobRole: "Hardware Engineer",
        jobLocation: "Mumbai",
        placementType: "Off-Campus",
        college: "ABC University"
    },
    {
        id: 16,
        name: "Student16",
        year: 2021,
        department: "ME",
        course: "B.Tech",
        specialization: "Manufacturing",
        cgpa: 9.66,
        company: "Google",
        ctc: 9,
        jobRole: "Mechanical Engineer",
        jobLocation: "Mumbai",
        placementType: "Off-Campus",
        college: "ABC University"
    },
    {
        id: 17,
        name: "Student17",
        year: 2020,
        department: "ME",
        course: "B.Tech",
        specialization: "Design Engineering",
        cgpa: 8.36,
        company: "Qualcomm",
        ctc: 6,
        jobRole: "Mechanical Engineer",
        jobLocation: "Pune",
        placementType: "Off-Campus",
        college: "ABC University"
    },
    {
        id: 18,
        name: "Student18",
        year: 2021,
        department: "CSE",
        course: "B.Tech",
        specialization: "ML",
        cgpa: 8.83,
        company: "Cisco",
        ctc: 20,
        jobRole: "Network Engineer",
        jobLocation: "Mumbai",
        placementType: "Off-Campus",
        college: "ABC University"
    },
    {
        id: 19,
        name: "Student19",
        year: 2020,
        department: "ME",
        course: "M.Tech",
        specialization: "Design Engineering",
        cgpa: 9.79,
        company: "Samsung",
        ctc: 17,
        jobRole: "Network Engineer",
        jobLocation: "Bangalore",
        placementType: "On-Campus",
        college: "ABC University"
    },
    {
        id: 20,
        name: "Student20",
        year: 2020,
        department: "CSE",
        course: "B.Tech",
        specialization: "ML",
        cgpa: 8.32,
        company: "Intel",
        ctc: 16,
        jobRole: "Network Engineer",
        jobLocation: "Delhi",
        placementType: "Off-Campus",
        college: "ABC University"
    },
    {
        id: 21,
        name: "Student21",
        year: 2021,
        department: "CSE",
        course: "B.Tech",
        specialization: "AI",
        cgpa: 8.5,
        company: "Google",
        ctc: 12,
        jobRole: "Software Engineer",
        jobLocation: "Bangalore",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 22,
        name: "Student22",
        year: 2021,
        department: "CSE",
        course: "M.Tech",
        specialization: "Cloud Computing",
        cgpa: 9.1,
        company: "Amazon",
        ctc: 15,
        jobRole: "Cloud Engineer",
        jobLocation: "Hyderabad",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 23,
        name: "Student23",
        year: 2021,
        department: "ECE",
        course: "B.Tech",
        specialization: "VLSI Design",
        cgpa: 7.9,
        company: "Intel",
        ctc: 8,
        jobRole: "Hardware Engineer",
        jobLocation: "Bangalore",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 24,
        name: "Student24",
        year: 2022,
        department: "ECE",
        course: "M.Tech",
        specialization: "Communication Systems",
        cgpa: 8.2,
        company: "Qualcomm",
        ctc: 10,
        jobRole: "Communication Engineer",
        jobLocation: "Hyderabad",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 25,
        name: "Student25",
        year: 2022,
        department: "ME",
        course: "B.Tech",
        specialization: "Thermal Engineering",
        cgpa: 7.6,
        company: "Tata Motors",
        ctc: 6,
        jobRole: "Mechanical Engineer",
        jobLocation: "Mumbai",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 26,
        name: "Student26",
        year: 2022,
        department: "ECE",
        course: "B.Tech",
        specialization: "Communication Systems",
        cgpa: 7.5,
        company: "Qualcomm",
        ctc: 13,
        jobRole: "Data Scientist",
        jobLocation: "Mumbai",
        placementType: "Off-Campus",
        college: "XYZ University"
    },
    {
        id: 27,
        name: "Student27",
        year: 2022,
        department: "ME",
        course: "B.Tech",
        specialization: "Thermal Engineering",
        cgpa: 8.2,
        company: "Facebook",
        ctc: 20,
        jobRole: "Network Engineer",
        jobLocation: "Chennai",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 28,
        name: "Student28",
        year: 2022,
        department: "CSE",
        course: "B.Tech",
        specialization: "ML",
        cgpa: 8.8,
        company: "Cisco",
        ctc: 14,
        jobRole: "Communication Engineer",
        jobLocation: "Hyderabad",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 29,
        name: "Student29",
        year: 2022,
        department: "ECE",
        course: "M.Tech",
        specialization: "Embedded Systems",
        cgpa: 8.1,
        company: "Qualcomm",
        ctc: 6,
        jobRole: "Software Engineer",
        jobLocation: "Bangalore",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 30,
        name: "Student30",
        year: 2022,
        department: "ME",
        course: "B.Tech",
        specialization: "Thermal Engineering",
        cgpa: 9.0,
        company: "Amazon",
        ctc: 16,
        jobRole: "Software Engineer",
        jobLocation: "Hyderabad",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 31,
        name: "Student31",
        year: 2022,
        department: "ME",
        course: "B.Tech",
        specialization: "Manufacturing",
        cgpa: 8.4,
        company: "Amazon",
        ctc: 15,
        jobRole: "Network Engineer",
        jobLocation: "Pune",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 32,
        name: "Student32",
        year: 2022,
        department: "ECE",
        course: "B.Tech",
        specialization: "Embedded Systems",
        cgpa: 6.2,
        company: "Microsoft",
        ctc: 7,
        jobRole: "Communication Engineer",
        jobLocation: "Delhi",
        placementType: "Off-Campus",
        college: "XYZ University"
    },
    {
        id: 33,
        name: "Student33",
        year: 2022,
        department: "CSE",
        course: "M.Tech",
        specialization: "Cybersecurity",
        cgpa: 9.4,
        company: "Qualcomm",
        ctc: 11,
        jobRole: "Network Engineer",
        jobLocation: "Pune",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 34,
        name: "Student34",
        year: 2022,
        department: "ME",
        course: "M.Tech",
        specialization: "Design Engineering",
        cgpa: 6.1,
        company: "Microsoft",
        ctc: 8,
        jobRole: "Data Scientist",
        jobLocation: "Bangalore",
        placementType: "Off-Campus",
        college: "XYZ University"
    },
    {
        id: 35,
        name: "Student35",
        year: 2022,
        department: "CSE",
        course: "B.Tech",
        specialization: "Cloud Computing",
        cgpa: 7.9,
        company: "Oracle",
        ctc: 13,
        jobRole: "Hardware Engineer",
        jobLocation: "Mumbai",
        placementType: "Off-Campus",
        college: "XYZ University"
    },
    {
        id: 36,
        name: "Student36",
        year: 2022,
        department: "ME",
        course: "B.Tech",
        specialization: "Manufacturing",
        cgpa: 9.6,
        company: "Google",
        ctc: 9,
        jobRole: "Mechanical Engineer",
        jobLocation: "Mumbai",
        placementType: "Off-Campus",
        college: "XYZ University"
    },
    {
        id: 37,
        name: "Student37",
        year: 2022,
        department: "ME",
        course: "B.Tech",
        specialization: "Design Engineering",
        cgpa: 8.3,
        company: "Qualcomm",
        ctc: 6,
        jobRole: "Mechanical Engineer",
        jobLocation: "Pune",
        placementType: "Off-Campus",
        college: "XYZ University"
    },
    {
        id: 38,
        name: "Student38",
        year: 2022,
        department: "CSE",
        course: "B.Tech",
        specialization: "ML",
        cgpa: 8.8,
        company: "Cisco",
        ctc: 20,
        jobRole: "Network Engineer",
        jobLocation: "Mumbai",
        placementType: "Off-Campus",
        college: "XYZ University"
    },
    {
        id: 39,
        name: "Student39",
        year: 2022,
        department: "ME",
        course: "M.Tech",
        specialization: "Design Engineering",
        cgpa: 9.7,
        company: "Samsung",
        ctc: 17,
        jobRole: "Network Engineer",
        jobLocation: "Bangalore",
        placementType: "On-Campus",
        college: "XYZ University"
    },
    {
        id: 40,
        name: "Student40",
        year: 2022,
        department: "CSE",
        course: "B.Tech",
        specialization: "ML",
        cgpa: 8.3,
        company: "Intel",
        ctc: 16,
        jobRole: "Network Engineer",
        jobLocation: "Delhi",
        placementType: "Off-Campus",
        college: "XYZ University"
    }
];
    

export default studentData;
